
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javaspringboot
 */
public class Main extends javax.swing.JFrame {
    
    public static ArrayList<String> productNames = new ArrayList<>();
    public static double[] prices = new double[100];
    public static HashMap<String,Integer> stockProducts = new HashMap<>();
    
    public static int pointerPrices = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductBtn = new javax.swing.JButton();
        listInventoryBtn = new javax.swing.JButton();
        butProductBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        lookProductForNameBtn = new javax.swing.JButton();
        getOutWithFinalTicketBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addProductBtn.setText("Agregar Producto");
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });

        listInventoryBtn.setText("Listar Inventario");

        butProductBtn.setText("Comprar producto");
        butProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butProductBtnActionPerformed(evt);
            }
        });

        reportsBtn.setText("Mostar estadisticas");

        lookProductForNameBtn.setText("Buscar producto por nombre");

        getOutWithFinalTicketBtn.setText("Salir con ticket final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getOutWithFinalTicketBtn)
                    .addComponent(lookProductForNameBtn)
                    .addComponent(reportsBtn)
                    .addComponent(butProductBtn)
                    .addComponent(addProductBtn)
                    .addComponent(listInventoryBtn))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(addProductBtn)
                .addGap(18, 18, 18)
                .addComponent(listInventoryBtn)
                .addGap(18, 18, 18)
                .addComponent(butProductBtn)
                .addGap(18, 18, 18)
                .addComponent(reportsBtn)
                .addGap(18, 18, 18)
                .addComponent(lookProductForNameBtn)
                .addGap(18, 18, 18)
                .addComponent(getOutWithFinalTicketBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed
        if(pointerPrices == 99){
            JOptionPane.showMessageDialog(rootPane, "Ya no se pueden ingresar mas productos porque ya no hay mas capacidad.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        
        String nameProduct = JOptionPane.showInputDialog(rootPane, "Ingrese el nombre del producto", "Ventana", JOptionPane.QUESTION_MESSAGE); 
        if(nameProduct == null) return;
        
        if(productNames.contains(nameProduct)){
            JOptionPane.showMessageDialog(rootPane, "El producto con nombre " + nameProduct + "ya esta registrado.", "Error", HEIGHT);
        }

        Double price = this.readDouble("Ingrese el precio del producto", "Ventana", JOptionPane.QUESTION_MESSAGE);            
        if(price == null) return;

        Integer stock = this.readInteger("Ingrese el stock del producto", "Ventana", JOptionPane.QUESTION_MESSAGE);
        if(stock == null) return;
        
        
        productNames.add(nameProduct);
        prices[pointerPrices] = price;
        stockProducts.put(nameProduct, stock);
        
        pointerPrices++;
        
        JOptionPane.showMessageDialog(rootPane, "Se ha agregado el producto exitosamente.", "Exito", JOptionPane.PLAIN_MESSAGE);
        
        
        
    }//GEN-LAST:event_addProductBtnActionPerformed

    
    public Integer readInteger(String message, String title, int typeOfMessage){
        boolean intPass = false;
        int number = 0;

        do{
            try{
                String intMessage = JOptionPane.showInputDialog(rootPane,message ,title, typeOfMessage);

                if(intMessage == null){
                    return null;
                }
                number = Integer.parseInt(intMessage);


                if(number < 0){
                    JOptionPane.showMessageDialog(rootPane,"Solo puedes ingresar numeros positivos");
                } else {
                    intPass = true;
                }

            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Haz ingresado un numero no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } while (!intPass);

        return number;
    }
    
    
    public Double readDouble(String message, String title, int typeOfMessage){
        boolean doublePass = false;
        double doubleNumber = 0;

        do{
            try{
                String doubleMessage = JOptionPane.showInputDialog(rootPane,message ,title, typeOfMessage);

                if(doubleMessage == null){
                    return null;
                }
                doubleNumber = Double.parseDouble(doubleMessage);


                if(doubleNumber < 0){
                    JOptionPane.showMessageDialog(rootPane,"Solo puedes ingresar numeros positivos decimales.");
                } else {
                    doublePass = true;
                }

            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Haz ingresado un numero decimal no valido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } while (!doublePass);

        return doubleNumber;
    }
    
    private void butProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butProductBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butProductBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBtn;
    private javax.swing.JButton butProductBtn;
    private javax.swing.JButton getOutWithFinalTicketBtn;
    private javax.swing.JButton listInventoryBtn;
    private javax.swing.JButton lookProductForNameBtn;
    private javax.swing.JButton reportsBtn;
    // End of variables declaration//GEN-END:variables
}
